[package]
name = "advent_of_code_2021"
version = "0.3.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1

[profile.test]
opt-level = 3

[dependencies]
itertools ="0.10"
num = "0.4"
structopt = "0.3"
thiserror = "1.0"
